Feature: Mapping project entities and relationships
eapg/EA_RESTAURANT pull request #149
Opened 2022-08-02 15:27 UTC by eapg

* Mapping project entities
* creating relationships between entities

2022-08-04 00:23 UTC, reynoldmorel requested changes

2022-08-04 00:23 UTC, reynoldmorel commented on src/tests/core/engine/app_engine_processor_integration_test.py
> +
Remove this change

2022-08-04 00:23 UTC, reynoldmorel commented on src/tests/core/engine/app_engine_processor_integration_test.py
> +from src.lib.entities.sqlalchemy_orm_mapping import UserEntity
Remove this change

2022-08-04 00:44 UTC, eapg commented on src/tests/core/engine/app_engine_processor_integration_test.py
> +
done

2022-08-04 00:45 UTC, eapg commented on src/tests/core/engine/app_engine_processor_integration_test.py
> +from src.lib.entities.sqlalchemy_orm_mapping import UserEntity
done

2022-08-04 15:09 UTC, reynoldmorel requested changes

2022-08-04 15:09 UTC, reynoldmorel commented on src/lib/entities/sqlalchemy_orm_mapping.py
> +add_created_and_updated_relationships(User)
I don't see `updated` and `created` for `AbstractEntity`

2022-08-06 02:51 UTC, reynoldmorel approved these changes

2022-08-06 02:51 UTC, merged