Featute: Adding method to validate ingredient availability
eapg/EA_RESTAURANT pull request #80
Opened 2022-05-17 14:29 UTC by eapg

* Adding method to validate ingredient availability
* Adding test for validate ingredient availability

This method will take two arguments(the **ingredient** to validate and the **quantity to use**) , with the **ingredient.id** the method filter inside the repository the **inventory_ingredient** that match with the **ingredient id**, after that it compare its **quantity** with the **quantity to use**, if **quantity** is higher that **quantity to use** the method return **True** otherwise return **False**.

2022-05-19 05:19 UTC, reynoldmorel requested changes

2022-05-19 05:19 UTC, reynoldmorel commented on src/lib/repositories/impl/inventory_ingredient_repository_impl.py
> +        self, inventory_id, ingredient, quantity_to_use
```suggestion
        self, inventory_id, ingredient_id, quantity_to_use
```

2022-05-19 05:19 UTC, reynoldmorel commented on src/lib/repositories/impl/inventory_ingredient_repository_impl.py
> +                    == ingredient.id
```suggestion
                    == ingredient_id
```

2022-05-19 05:19 UTC, reynoldmorel commented on src/lib/repositories/inventory_ingredient_repository.py
> +    def validate_ingredient_availability(self, inventory_id, ingredient, quantity_to_use):
```suggestion
    def validate_ingredient_availability(self, inventory_id, ingredient_id, quantity_to_use):
```

2022-05-19 05:19 UTC, reynoldmorel commented on src/tests/lib/repositories/impl/inventory_ingredient_repository_impl_test.py
> +                inventory_1.id, ingredient_1, 5
```suggestion
                inventory_1.id, ingredient_1.id, 5
```

2022-05-19 05:19 UTC, reynoldmorel commented on src/tests/lib/repositories/impl/inventory_ingredient_repository_impl_test.py
> +                inventory_1.id, ingredient_1, 15
```suggestion
                inventory_1.id, ingredient_1.id, 15
```

2022-05-19 13:00 UTC, eapg commented
Done.

2022-05-19 13:06 UTC, eapg commented on src/lib/repositories/impl/inventory_ingredient_repository_impl.py
> +        self, inventory_id, ingredient, quantity_to_use
done

2022-05-19 13:06 UTC, eapg commented on src/lib/repositories/impl/inventory_ingredient_repository_impl.py
> +                    == ingredient.id
done

2022-05-19 13:06 UTC, eapg commented on src/lib/repositories/inventory_ingredient_repository.py
> +    def validate_ingredient_availability(self, inventory_id, ingredient, quantity_to_use):
done

2022-05-19 13:06 UTC, eapg commented on src/tests/lib/repositories/impl/inventory_ingredient_repository_impl_test.py
> +                inventory_1.id, ingredient_1, 5
done

2022-05-19 13:06 UTC, eapg commented on src/tests/lib/repositories/impl/inventory_ingredient_repository_impl_test.py
> +                inventory_1.id, ingredient_1, 15
done

2022-05-21 17:50 UTC, reynoldmorel approved these changes

2022-05-21 18:07 UTC, merged