Feature: Adding order status history entity and repository
eapg/EA_RESTAURANT pull request #85
Opened 2022-05-18 19:13 UTC by eapg

* Adding order status history entity
* Adding order status history repository

This entity will be use to develop a mechanism to manage the order status throght the different status that an order have and the time when the status change.

2022-05-19 05:22 UTC, reynoldmorel requested changes
Could you add tests here?

2022-05-19 05:22 UTC, reynoldmorel commented on src/lib/entities/order_status_history.py
> +        self.update_by = None  # obj
```suggestion
```

2022-05-19 13:41 UTC, eapg commented on src/lib/entities/order_status_history.py
> +        self.update_by = None  # obj
done

2022-05-21 17:52 UTC, reynoldmorel approved these changes

2022-05-21 18:08 UTC, merged